<?php

/**
 * @file
 * Contains mpp_layouts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mpp_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mpp_layouts module.
    case 'help.page.mpp_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('mpp Layouts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mpp_layouts_theme() {
  return [
    'mpp_layouts' => [
      'render element' => 'children',
    ],
  ];
}
